name: cyberchef
title: CyberChef
base: core24
adopt-info: cyberchef
summary: The Cyber Swiss Army Knife for encryption, encoding, compression and analysis.
description: |
  CyberChef is a simple, intuitive web app for carrying out all manner of "cyber" operations within a web browser. These operations include simple encoding like XOR and Base64, more complex encryption like AES, DES and Blowfish, creating binary and hexdumps, compression and decompression of data, calculating hashes and checksums, IPv6 and X.509 parsing, changing character encodings, and much more.

  The tool is designed to enable both technical and non-technical analysts to manipulate data in complex ways without having to deal with complex tools or algorithms. It was conceived, designed, built and incrementally improved by an analyst in their 10% innovation time over several years.

icon: cyberchef.png

grade: stable
confinement: strict
compression: lzo

license: GPL-3.0-or-later
source-code: https://github.com/gchq/CyberChef
issues: https://github.com/JitPatro/CyberChef-Snap/issues

architectures:
  - build-on: amd64
  - build-on: arm64
  - build-on: armhf

parts:
  cyberchef:
    plugin: nil
    source: .
    build-packages:
      - unzip
      - wget

    override-build: |
      wget https://github.com/gchq/CyberChef/releases/latest
      VERSION=`cat latest| grep "Release" | head -n 1 | cut "-d " -f 4`
      craftctl set version=${VERSION}
      wget "https://github.com/gchq/CyberChef/releases/download/${VERSION}/CyberChef_${VERSION}.zip"
      unzip CyberChef_${VERSION}.zip -d $CRAFT_PART_INSTALL/
      mv $CRAFT_PART_INSTALL/CyberChef_${VERSION}.html $CRAFT_PART_INSTALL/index.html
      cp ./server.py  $CRAFT_PART_INSTALL/
      echo -e '#!/bin/bash\n\nset -e\n\nnohup python3 $SNAP/server.py &>/dev/null &\n\nsleep 0.3 && xdg-open http://localhost:9090' > $CRAFT_PART_INSTALL/cyberchef
      chmod +x $CRAFT_PART_INSTALL/cyberchef

apps:
  cyberchef:
    command: cyberchef
    plugs: [desktop, network, network-bind]
